server:
  port: 8306
#  servlet:
#    context-path: /mobile
eureka:
  client:
    serviceUrl:
      register-with-eureka: true     #发现Eureka服务注册中心注册的服务提供者 （如果为false则为不进行注册消费者服务）
      defaultZone: http://eureka7001.com:7001/eureka/

  instance:
    instance-id: auth-service-8306    #设置eureka客户端status状态名称
    prefer-ip-address: true     #访问路径可以显示IP地址
# 配置该状态url:的显示内容
info:
  project.name: springcloud-auth-service(关联授权服务)
  app.name: springcloud-xu-message
  project.description: 该项目服务的主要功能：登陆的时候可以进行关联授权，方便下一次登陆快捷
  build.artifactId: springcloud-auth-service
  build.version: 0.0.1-SNAPSHOT

  spring:
    spring:
      freemarker:
        suffix: .ftl
        #    templateEncoding: UTF-8
        templateLoaderPath: classpath:/templates/
        enabled: true
        charset: UTF-8
    application:
      name: auth-service

  redis:
    host: 192.168.10.146
    port: 6379
    jedis:
      pool:
        max-active: 1000
        max-idle: 100
        min-idle: 1
        max-wait: 10s

  datasource:
    name: test
    url: jdbc:mysql://192.168.10.146:3306/auth_service?useUnicode=true&characterEncoding=utf-8&useSSL=false              # 数据库名称
    username: root
    password: admin
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #    filters: stat
    tomcat:
      maxActive: 20
      maxWait: 60000
      max-idle: 10
      initial-size: 5
    dbcp2:
      initialSize: 1
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      max-wait-millis: 60000


feign:
  hystrix:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000
        loggerLevel: basic



#mybatis的配置信息
mybatis:
  # 指定全局配置文件位置
  #  config-location: classpath:mybatis/mybatis-config.xml
  # 指定sql映射文件位置
  #  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    #    map-underscore-to-camel-case: true
    mapUnderscoreToCamelCase: true


#日志打印到控制台
logging:
  level:
    com.xu.springcloud.shop.member.dao: debug