server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false
    fetchRegistry: false
    serviceUrl:
      # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      # 配置Eureka集群7001需要配置7002和7003
#      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/